import re
email_data="Harshith <harshithkngowda96@gmail.com>, divya <divya@gmail.com>"
result= re.search(r"Ha", email_data)
print(result)
result= re.findall(r"sh", email_data)
print(result)
result= re.search(r"ha[d,h]", email_data)
print(result)
result= re.search(r"ha[a-z]{3}", email_data)
print(result)
result= re.search(r"ha[a-z]+", email_data)
print(result)
result= re.search(r"[A-Za-z0-9_]+@[A-Za-z0-9]+\.[a-z]+", email_data)
print(result)
result= re.findall(r"[A-Za-z0-9_]+@[A-Za-z0-9]+\.[a-z]+", email_data)
print(result)
result= re.findall(r"[A-Za-z0-9_]+", email_data)
print(result)
result= re.search(r"\w+@\w+\.\w+", email_data)
print(result)
result= re.search(r"(\w)+@(\w)+\.(\w+)", email_data)
print(result)
result= re.findall(r"(\w+)@(\w+)\.(\w+)", email_data)
print(result,result[0])
